services:
  - type: web
    name: fintrend-backend
    env: node
    rootDir: Project_Trendboard_backend/fintrend-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
      - key: FRONTEND_URL
        value: https://fintrendai.vercel.app/,http://localhost:5173
